name: 'Setup Emacs'
description: 'Install a specific Emacs version for use in your workflow.'
author: 'Jen-Chieh Shen'
inputs:
  version:
    description: 'The version of Emacs to install, e.g. "24.3", or "snapshot" for a recent development version.'
runs:
  using: composite
  steps:
  - if: runner.os != 'Windows'
    uses: purcell/setup-emacs@master
    with:
      version: ${{ inputs.version }}
  - if: runner.os == 'Windows'
    uses: jcs090218/setup-emacs-windows@master
    with:
      version: ${{ inputs.version }}
